try:
    print(is_good_password('123456789A'))
except Exception as err:
    print(type(err))